version: 2
Jobs:
  one:
    docker:
      -image: cimg/ruby:3.0.2
       auth:
          username: mydockerhub-user
          password: SDOCKERHUB PASSWORD 
    steps:
      -checkout
      -run: echo "A first hello"
      -run: mkdir p my_workspace
      -run: echo "Trying out workspaces" > my_workspace/echo-output
      -persist to workapace:
          root: my workspace
          paths:
            -echo-output
two:
  docker:
    -image: cing/ruby:3.0.2
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB PASSWORD 
  steps:
    -checkout
    -run: echo "A more familiar hi"
    -attach workspace:
      at: my workspace
      run:
        if [ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
        echo "It worked!";
       else
          echo "Nope!"; exit 1
        fi
workflows:
 version: 2
 one and two:
 jobs:
  -one
  -two:
    requires:
      -one
